name: my-workflow

on:
  push:
    branches:
      - test-pull-request-to
      - test-pull-request-from

jobs:
  job-one:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }} # Dynamically set environment name
    env:
      ENV_VAR: ${{ vars.TEST }} # Access environment-specific secret
    steps:
      - name: Your build/deploy steps
        run: echo "Using secret ${{env.ENV_VAR}} in environment ${{ github.head_ref || github.ref_name }}"