name: Testing Multi Branch Pull Requests
on:
  pull_request:
    types:
      - opened
jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: echo "Running workflow from ${{github.ref_name}} branch"
